postgresConfig : "postgres://user:mysecretpassword@localhost:3000/postgres?sslmode=disable"
port : "8080"
numberOfTopEntriesToConsider : 10
numberOfLastEntriesToConsiderWhenSearchingByTag : 50
salt : "eoriu69045trhgeo4t5780ejr9t78340gjtu9eu9034oij490et74564564asdas8dgyas8d68743r584frth437ry49r58478r5984r984rewhf8943hf349yfg34921eu23ru3efr4eftu43t784tf980eufg8u4f4uft"
cachePeriod : 1800
commonCacheTag : "default"